In [1]:
import numpy as np

In [2]:
# Q1

In [3]:
a1 = np.array([0,1,2,3,4,5,6,7,8])
a1 = a1.reshape(3,-1)

In [4]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# Q2

In [6]:
a2 = np.array([0,1,2,3,4,5,6,7,8,9])
for i in range(len(a2)):
    if a2[i] % 2 == 1:
        a2[i] = -1

In [7]:
# a2[a2%2 == 1] = -1
# This is another way to do that, that's mad lol

In [8]:
a2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
# Q3

In [10]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [11]:
# Q4

In [12]:
a4 = np.arange(100).reshape(5,-1)

In [13]:
a4[:, :4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])