In [1]:
import numpy as np

In [2]:
# Q1: Convert a 1-D array into a 2-D array with 3 rows.

In [3]:
a1 = np.array([0,1,2,3,4,5,6,7,8])
a1 = a1.reshape(3,-1)

In [4]:
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# Q2: Replace all odd numbers in the given array with -1

In [6]:
a2 = np.array([0,1,2,3,4,5,6,7,8,9])
for i in range(len(a2)):
    if a2[i] % 2 == 1:
        a2[i] = -1

In [7]:
# a2[a2%2 == 1] = -1
# This is another way to do that, that's mad lol

In [8]:
a2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
# Q3: Find the positions of: elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y.

In [10]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(f"{np.where(x > y)} and {np.where(x == y)}")

(array([1, 2, 4, 5, 6, 7, 8, 9]),) and (array([0]),)


In [11]:
# Q4: Extract the first four columns of this 2-D array.

In [12]:
a4 = np.arange(100).reshape(5,-1)

In [13]:
a4[:, :4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [14]:
# Additional Questions

In [15]:
# Q1: Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).
aa1 = np.random.randint(30,41,10)
print(aa1)

[36 38 37 34 38 33 33 35 37 39]


In [16]:
"""Q2: Consider the following matrices :
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))
Write a python program to perform the following using Numeric Python (numpy).
i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.
ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C
iii) Product of two matrices A and B, and print the resultant matrix D
iv) Sort the elements of resultant matrix C and print the resultant Matrix E.
v) Transpose the Matrix E and print the result"""

A = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 10)))
B = np.array(((7, 8, 10) ,(4, 5, 6), (1, 2, 3)))

C = A + B
E = A - B
print("C:\n", C)
print("\nE:\n", E)

print("\nSum(A):\n", np.sum(A))
print("\nColsum(B):\n", np.sum(B, axis=0))
print("\nRowsum(C):\n", np.sum(C, axis=1))

D = np.dot(A, B)
print("\nDot(A, B):\n", D)

E = np.sort(C,axis=None).reshape((3,3))
print("\nSort(C):\n", E)

print("\nTranspose(E):\n", E.T)

C:
 [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

E:
 [[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]

Sum(A):
 46

Colsum(B):
 [12 15 19]

Rowsum(C):
 [31 30 31]

Dot(A, B):
 [[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]

Sort(C):
 [[ 8  8  8]
 [10 10 10]
 [12 13 13]]

Transpose(E):
 [[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
